### ISSUE TITLE
Problems with Data Dictionary product

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/ontology-publisher#23]
Here is the list of issues I found looking at https://spec.edmcouncil.org/fibo/glossary/master/latest/glossary-dev.xlsx:

1. Some rows have dislocated columns. This results in the wrong types like "ordinary share" (for common share-US). This may be due to the problems with processing of rich text that includes tabs or some other kind of separator.
2. There are duplicated rows and values in "Terms" column, e.g., "absolute prepayment rate has value"
3. Some types are wrong. For example, "absolute prepayment rate has value" has two types, one of which "Individual" is incorrect. In fact most of duplicates looks as if they were related to that issue.
4. Many rows have no generated definitions although they may have ones, e.g., Blue-Sky law.
5. Some resources seem to be missing. The current FIBO Quick Start Development has more than 2500 classes while  FIBO Data Dictionary has little more than 1000.
6. I think we should have the column with the IRIs for the resources.
7. Perhaps we should also have the columns for the domain, module and ontology in which a given resource is defined.
8. Perhaps we should use the qualified names (of the respective properties) as the column headings (wherever it is possible). For instance, instead of "Terms" we would have "rdfs:label", etc.
Also the script that creates these products has a lot of commented out code.

**Comment by trypuz** [comment]
Closed due to #24
