### ISSUE TITLE
Missing labels for object properties in Vocabulary

### ISSUE THREAD

**Issue by kptyson** [edmcouncil/ontology-publisher#28]
The following query produces 217 results when executed against the 2020q3 ontology and vocabulary graphs.  I think these elements are supposed to have some form of label.  None of them appear to.  Not that this is catastrophic given the rigorous approach to IRI construction.

PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  *
WHERE
  { { ?concept  skos:definition  ?def }
    MINUS
      { ?concept skos:prefLabel|rdfs:label ?lbl }
  }

[Missinglabels.xlsx](https://github.com/edmcouncil/fibo/files/5593805/Missinglabels.xlsx)

**Comment by mereolog** [comment]
This is fixed due to the latest changes in ontology-publisher, i.e., the query returns no results.
