### ISSUE TITLE
The cognitive dissonance caused by the class hierarchy in the ontology and the concept hierarchy in the vocabulary

### ISSUE THREAD

**Issue by kptyson** [edmcouncil/ontology-publisher#32]
The FIBO ontology contains entities structured using the rdfs:subClassOf predicate.  This is a transitive predicate.  The FIBO vocabulary contains concepts structured using the skos:broader predicate which is an intransitive predicate.  The FIBO vocabulary is generated from the ontology.  The mapping is reflected in the use of the rdfs:isDefinedBy predicate mapping concepts to entities.  Due to the difference in transitivity, this is a lossy mapping.  This creates a problem for the user who seeks to use the FIBO vocabulary in conjunction with their own domain-specific vocabulary.  Reference data vendors would be an example of such users.  As it stands, the generated FIBO vocabulary implicitly makes skos:broader a transitive predicate depriving the vocabulary user of an intransitive extension point thereby forcing them to make an ontological commitment to the entirety of the FIBO ontology.

This could be fixed by generating the vocabulary with skos:broaderTransitive in addition to skos:broader which would leave the design decision on coupling to the end user.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra, will this cause duplication of directSubClassOf triples or other adverse effects?

Asserting them in the ontology will not have any direct negative effects. In fact the DirectTypeInferencer in RDF4J currently works by asserting these triples into the store itself. The only difference is that the inferencer marks them as inferred statements, and if you assert them yourself, they will become explicit. But asserting them yourself, even in combination with use of the direct type inferencer, will not cause any duplication unless perhaps you assert as part of a named graph.
