### ISSUE TITLE
Product formerly known as "Data dictionary"

### ISSUE THREAD

**Issue by dallemang** [edmcouncil/ontology-publisher#33]
On the previous FIBO site, there was a set of products called "data dictionary" that is quite different from the FIBO viewer and from the current Data Dictionary.  This was produced in response to specific user requests.  The code for this still exists (and for all I know, it is still being produced by the docker image of the publisher).  We should come up with a name for this, and how to present it on the website.

**Comment by trypuz** [comment]
Closed due to #24
