### ISSUE TITLE
Need for single mechanism for ontology collation

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/ontology-publisher#66]
We need a single mechanism to collate all FIBO ontologies, including all ontologies transitively imported by them.

**Comment by przemekgradzki** [comment]
What do you think about [ROBOT Merge](http://robot.obolibrary.org/merge)?

**Comment by mereolog** [comment]
I run 
`robot merge --input ../fibo/AboutFIBODev.rdf --output fibo_dev_merged.owl `
on fibo (commit ebf8739bd2cbe4b44dc18461f3865365182750b5) and got this error:
`Could not load imported ontology: <https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MortgageBackedSecurities/> Cause: ../fibo/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf (No such file or directory)`
Debug gave me this:
```
DEBUG Missing exception ID: Could not load imported ontology: <https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MortgageBackedSecurities/> Cause: ../fibo/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf (No such file or directory)
Could not load imported ontology: <https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MortgageBackedSecurities/> Cause: /Users/pawel.garbacz/Documents/edmc/github/edmc/fibo/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf (No such file or directory)
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MortgageBackedSecurities/> Cause: ../fibo/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
```
No idea why this happened.

**Comment by przemekgradzki** [comment]
@mereolog 
try to run:
`robot merge -vvv --input ../fibo/AboutFIBODev.rdf --output fibo_dev_merged.owl`

the first line of output looks like this:

> DEBUG Loading ontology ../fibo/AboutFIBODev.rdf with catalog file ../fibo/catalog-v001.xml

`robot` uses `catalog-v001.xml` file. See [... uri="./SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf" ...](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/catalog-v001.xml#L255) - there is **no such file**:
[./SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf)
Instead there is:
[./SEC/Debt/MortgageBackedSecurities.rdf](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/SEC/Debt/MortgageBackedSecurities.rdf)

The same problem (missing file) applies to all lines referring to the directory _./SEC/Debt/AssetBackedSecurities/_ - see [here](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/catalog-v001.xml#L252-L257)

**Comment by mereolog** [comment]
> @mereolog try to run: `robot merge -vvv --input ../fibo/AboutFIBODev.rdf --output fibo_dev_merged.owl`
> 
> the first line of output looks like this:
> 
> > DEBUG Loading ontology ../fibo/AboutFIBODev.rdf with catalog file ../fibo/catalog-v001.xml
> 
> `robot` uses `catalog-v001.xml` file. See [... uri="./SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf" ...](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/catalog-v001.xml#L255) - there is **no such file**: [./SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf) Instead there is: [./SEC/Debt/MortgageBackedSecurities.rdf](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/SEC/Debt/MortgageBackedSecurities.rdf)
> 
> The same problem (missing file) applies to all lines referring to the directory _./SEC/Debt/AssetBackedSecurities/_ - see [here](https://github.com/edmcouncil/fibo/blob/ebf8739bd2cbe4b44dc18461f3865365182750b5/catalog-v001.xml#L252-L257)

This fixes the problem.

**Comment by mereolog** [comment]
As far as I can tell robot cannot keep imported ontologies as separated resources in the merged file, e.g., if an imported ontology has a triple ABC rdf:type owl:Ontology, then this triple is not to be found in the merge.

This is a problem for us because one of the hygiene tests checks whether all resources have types and robot will render all ontologies typeless, so every reference to them will create an error:

```
ERROR:https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/NorthAmericanJurisdiction/MXGovernmentEntitiesAndJurisdictions/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/DER/DerivativesContracts/SwapsIndividuals/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/NorthAmericanJurisdiction/CAGovernmentEntitiesAndJurisdictions/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/NorthAmericanJurisdiction/USGovernmentEntitiesAndJurisdictions/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Guaranty/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt/ is referenced by isDefinedBy but has no type.
ERROR:https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies/ is referenced by isDefinedBy but has no type.
```
