### ISSUE TITLE
Problems with robot use in vocabulary product

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/ontology-publisher#94]
Use of robot in 
https://github.com/edmcouncil/ontology-publisher/blob/34c20ff39b68b787f544338d10ba9c6fa9f1a5fe/publisher/product/vocabulary/build.sh#L51 
and in
https://github.com/edmcouncil/ontology-publisher/blob/34c20ff39b68b787f544338d10ba9c6fa9f1a5fe/publisher/product/vocabulary/build.sh#L57
consistently gives this error:
`Could not load imported ontology: <https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/> Cause: Corrupt GZIP trailer `
See: 
https://jenkins.edmcouncil.org/job/fibo/job/DER-129/3/consoleFull
https://jenkins.edmcouncil.org/job/fibo/job/DER-129/2/consoleFull
This is odd since https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/ is resolvable.

A similar situation occurs in the other uses of robot, i.e., when quick versions of FIBO are produced.

**Comment by przemekgradzki** [comment]
it looks like a java runtime bug used in the current (Apr 11, 2022 at 12:19 pm) [ontology-publisher:stable](https://hub.docker.com/layers/ontology-publisher/edmcouncil/ontology-publisher/stable/images/sha256-535cea07c8aa7a2830729bdfa885beaf8c81cdba9689ce54534941c26f8542b6?context=explore) docker image.

I was able to reproduce the error in the current docker image:
`$ java -version`
> openjdk version "11.0.14" 2022-01-18
> OpenJDK Runtime Environment (build 11.0.14+9-alpine-r0)
> OpenJDK 64-Bit Server VM (build 11.0.14+9-alpine-r0, mixed mode)

however, after rebuilding the docker image:
`$ java -version`
> openjdk version "11.0.15" 2022-04-19
> OpenJDK Runtime Environment (build 11.0.15+10-alpine-r0)
> OpenJDK 64-Bit Server VM (build 11.0.15+10-alpine-r0, mixed mode)

the problem **does not occur**.

**Solution**: rebuild and publish the image `ontology-publisher:stable`

**Comment by mereolog** [comment]
> it looks like a java runtime bug used in the current (Apr 11, 2022 at 12:19 pm) [ontology-publisher:stable](https://hub.docker.com/layers/ontology-publisher/edmcouncil/ontology-publisher/stable/images/sha256-535cea07c8aa7a2830729bdfa885beaf8c81cdba9689ce54534941c26f8542b6?context=explore) docker image.
> 
> I was able to reproduce the error in the current docker image: `$ java -version`
> 
> > openjdk version "11.0.14" 2022-01-18
> > OpenJDK Runtime Environment (build 11.0.14+9-alpine-r0)
> > OpenJDK 64-Bit Server VM (build 11.0.14+9-alpine-r0, mixed mode)
> 
> however, after rebuilding the docker image: `$ java -version`
> 
> > openjdk version "11.0.15" 2022-04-19
> > OpenJDK Runtime Environment (build 11.0.15+10-alpine-r0)
> > OpenJDK 64-Bit Server VM (build 11.0.15+10-alpine-r0, mixed mode)
> 
> the problem **does not occur**.
> 
> **Solution**: rebuild and publish the image `ontology-publisher:stable`

So go for it.

**Comment by przemekgradzki** [comment]
Fixed - see https://jenkins.edmcouncil.org/job/fibo/job/master/502/consoleFull
